name: Laravel CI

on:
  push:
    branches:
      - main

jobs:
  laravel-tests:
    runs-on: ubuntu-24.04

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_database
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Navigate to project directory
      run: cd appLaravel

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2
        extensions: mbstring, bcmath, pdo, pdo_mysql
        coverage: none

    - name: Install Composer dependencies
      run: |
        cd appLaravel
        composer install --no-progress --prefer-dist

    - name: Set up .env file
      run: |
        cp appLaravel/.env.example appLaravel/.env
        php artisan key:generate --ansi
        sed -i 's/DB_HOST=127.0.0.1/DB_HOST=127.0.0.1/' appLaravel/.env
        sed -i 's/DB_DATABASE=laravel/DB_DATABASE=test_database/' appLaravel/.env
        sed -i 's/DB_USERNAME=root/DB_USERNAME=root/' appLaravel/.env
        sed -i 's/DB_PASSWORD=/DB_PASSWORD=root/' appLaravel/.env

    - name: Run migrations
      run: |
        cd appLaravel
        php artisan migrate --force

    - name: Run tests
      run: |
        cd appLaravel
        vendor/bin/phpunit --testdox
