name: Laravel CI

on:
  push:
    branches:
      - main

jobs:
  laravel-tests:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2
        extensions: mbstring, bcmath, pdo, pdo_mysql

    - name: Install Composer
      run: |
        curl -sS https://getcomposer.org/installer | php
        sudo mv composer.phar /usr/local/bin/composer

    - name: Install Laravel Project with Composer
      run: composer create-project --prefer-dist laravel/laravel App

    #- name: Navigate to Laravel Project
     # run: cd App

    - name: Navigate to Laravel Project
      working-directory: ./App
      run: |
        composer install --no-progress --prefer-dist
        cp .env.example .env
        php artisan key:generate --ansi

    - name: Install NPM dependencies
      working-directory: ./App
      run: |
        npm install
        npm run dev
